name: Build and deploy RecipeGo backend in test environment

env:
  AWS_REGION: "eu-west-2"

on:
  push:
    branches-ignore:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: Read build directories
        id: build-dirs
        run: |
          BUILD_DIRS=$(cat build_dirs.txt | tr '\n' ',' | sed 's/,$//')
          echo "dirs=$BUILD_DIRS" >> $GITHUB_OUTPUT
          echo "Build directories: $BUILD_DIRS"

      - name: setup docker build
        uses: docker/setup-buildx-action@v3

      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          role-session-name: github-ci
          aws-region: ${{env.AWS_REGION}}

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: run utils unit tests
        working-directory: backend/utils
        run: go test -v ./...

      - name: run unit tests for models
        working-directory: backend/models
        run: go test -v ./...

      - name: build go bins for lambda
        run: |
          docker build --build-arg BUILD_DIRS="${{ steps.build-dirs.outputs.dirs }}" -t recipe_go .
          docker create --name extract-builder recipe_go
          rm -rf ./bin
          docker cp extract-builder:/app/bin ./bin
          docker rm extract-builder

      - name: deploy sam
        run: |
          sam deploy \
            --template-file template.yaml \
            --s3-bucket recipe-go-sam-${{ env.AWS_REGION }}-test \
            --stack-name recipe-stack \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --region ${{env.AWS_REGION}} \
            --parameter-overrides EnvironmentName=test \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
